name: Dusk Tests
on: workflow_dispatch

permissions:
  contents: write

jobs:

  dusk-php:
    runs-on: ubuntu-latest
    env:
      APP_URL: "http://127.0.0.1:8000"
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: log
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - name: Prepare The Environment
        run: cp .env.example .env
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE \`pr0poll\` character set UTF8mb4 collate utf8mb4_bin;"
      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_extensions: intl zip sodium pcntl bcmath
          php_version: "8.2"
          args: --ignore-platform-req=ext-pcntl --ignore-platform-req=ext-bcmath --no-progress --prefer-dist --optimize-autoloader
      - name: Change Permissions
        id: change_permissions
        run: sudo chmod -R 755 vendor
      - name: Generate Application Key
        id: generate_key
        run: php artisan key:generate
      - name: Upgrade Chrome Driver
        id: upgrade_chrome_driver
        run: sudo php artisan dusk:chrome-driver --detect
      - name: Start Chrome Driver
        id: start_chrome_driver
        run: sudo ./vendor/laravel/dusk/bin/chromedriver-linux &
      - name: Run Laravel Server
        if: success() && steps.change_permissions.outcome == 'success' && steps.generate_key.outcome == 'success' && steps.upgrade_chrome_driver.outcome == 'success' && steps.start_chrome_driver.outcome == 'success'
        run: sudo php artisan serve --no-reload &
      - name: Run Dusk Tests
        if: success() && steps.change_permissions.outcome == 'success' && steps.generate_key.outcome == 'success' && steps.upgrade_chrome_driver.outcome == 'success' && steps.start_chrome_driver.outcome == 'success'
        run: sudo php artisan dusk
      - name: Upload Screenshots
        if: failure() && steps.change_permissions.outcome == 'success' && steps.generate_key.outcome == 'success' && steps.upgrade_chrome_driver.outcome == 'success' && steps.start_chrome_driver.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
