name: "Fix Code Styling"

on:
  push:
    paths:
      - '**.php'
      - 'resources'
  pull_request:
    paths:
      - '**.php'
      - 'resources'

permissions:
  contents: write

jobs:
  fix-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_extensions: intl zip

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.3.1

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
