name: "JavaScript Code Linting"

on:
  push:
    branches:
      - 'refactor/code-quality'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install

      - name: ESLint
        run: npm run lint
